spring:
  profiles: default
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Database/sms_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update